# Generated by Django 4.1.4 on 2023-02-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='image',
            field=models.ImageField(default='null.jpg', upload_to='sample'),
        ),
    ]
