# Generated by Django 4.1.4 on 2023-02-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addapp', '0002_storage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipename', models.CharField(max_length=40)),
                ('recipeingredients', models.CharField(max_length=50)),
                ('recipeprice', models.IntegerField()),
                ('image', models.ImageField(upload_to='sample')),
            ],
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
