# Generated by Django 4.1.4 on 2023-02-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addapp', '0003_recipe_delete_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='null.jpg', upload_to='sample'),
        ),
    ]
