# Generated by Django 4.1.4 on 2023-02-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addapp', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=40)),
                ('categoryimage', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=67)),
                ('productprice', models.IntegerField()),
                ('productimage', models.ImageField(upload_to='product')),
                ('category', models.CharField(max_length=89)),
            ],
        ),
    ]
