# Generated by Django 4.1.4 on 2023-02-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=34)),
                ('middlename', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=56)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=69)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
