# Generated by Django 4.1.4 on 2023-02-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='null', max_length=72),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='null', max_length=67),
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.CharField(max_length=70),
        ),
    ]
